server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true